:zap: adding validation of results to github actions

diff --git a/.github/workflows/results.yml b/.github/workflows/results.yml
--- a/.github/workflows/results.yml
+++ b/.github/workflows/results.yml
@@ -1,4 +1,4 @@
-name: testing
+name: results
 
 on: [push]
 jobs:
@@ -7,7 +7,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.10", "3.11"]
+        python-version: ["3.11"]
     steps:
     - uses: actions/checkout@v3
     - name: Install poetry
@@ -24,4 +24,13 @@ jobs:
     - name: Testing
       run: |
         poetry env info
-        poetry run pytest
+        ERRORS=errors.txt
+        for CSV in results/*.csv; do
+            echo "Validating $CSV"
+            poetry run vanjari validate-csv --csv "$CSV" --errors "$ERRORS"
+            if [ -f "$ERRORS" ]; then
+                echo "Error: $CSV has errors"
+                cat "$ERRORS"
+                exit 1
+            fi
+        done
